name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(Date:yy).$(Date:MM).$(Date:dd)$(Rev:.r)

trigger:
- main
- feature/*

pool:
  name: TRADING-DOTNET-02

steps:
- task: PowerShell@2
  displayName: 'Versioning manifest'
  inputs:
    filePath: '$(Build.SourcesDirectory)\UpdateVersion.ps1'
    arguments: '-ProjectDir "$(Build.SourcesDirectory)" -BuildNumber "$(Build.BuildNumber)"'

- task: CopyFiles@2
  displayName: 'Copy Files to DROP'
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: drop 'Publish Artifact DROP'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'FilePath'
    TargetPath: '$(DropFolder)\$(Build.DefinitionName)\$(Build.BuildNumber)'
