name: DOrcDeployModule-build

on:
  push:
    branches:
      - '**'
      - 'feature/*'
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    name: ${{ github.event.repository.name }}_${{ github.ref_name }}_${{ github.run_number }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Versioning manifest
        run: |
          $Env:BUILD_BUILDNUMBER = "$(Get-Date -Format 'yy.MM.dd').$Env:GITHUB_RUN_NUMBER"
          Write-Host "Running UpdateVersion.ps1 with new module version $Env:BUILD_BUILDNUMBER"
          pwsh ./UpdateVersion.ps1 -BuildNumber $Env:BUILD_BUILDNUMBER
        shell: pwsh

      - name: Copy updated files
        id: copy_files  # Add an ID to reference outputs from this step
        run: |
          $destinationDir = "$Env:GITHUB_WORKSPACE\DOrcDeployModule"
          Write-Host "Copying file to $destinationDir"
          if (-Not (Test-Path $destinationDir)) {
              New-Item -ItemType Directory -Path $destinationDir
          }

          Copy-Item -Path "./*.psd1" -Destination "$destinationDir" -Force
          Copy-Item -Path "./*.psm1" -Destination "$destinationDir" -Force

          Write-Host "Copied files:"
          Get-ChildItem -Path $destinationDir
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DOrcDeployModule
          path: ${{ github.workspace }}/DOrcDeployModule/*
          
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
